# Generated by Django 2.1.7 on 2019-06-22 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_account_user'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='games', through='accounts.Account', to=settings.AUTH_USER_MODEL, verbose_name='Игроки'),
        ),
    ]
