# Generated by Django 2.1.7 on 2019-03-23 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Ожидание'), (1, 'Завершен'), (2, 'Отменен')], default=0, verbose_name='Статус')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.Game', verbose_name='Игра')),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='game.Player', verbose_name='Проигравший')),
                ('tournament', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament', verbose_name='Турнир')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='game.Player', verbose_name='Победитель')),
            ],
            options={
                'db_table': 'core_match',
            },
        ),
    ]
